/** search repository action type
 *
 *
 */

export const SEARCH_REPOSITORY ='SEARCH_REPOSITORY';
export type SEARCH_REPOSITORY = typeof SEARCH_REPOSITORY;
export const SEARCHING_REPOSITORY ='SEARCHING_REPOSITORY';
export type SEARCHING_REPOSITORY = typeof SEARCHING_REPOSITORY;
export const SEARCH_REPOSITORY_SUCCESS ='SEARCH_REPOSITORY_SUCCESS';
export type SEARCH_REPOSITORY_SUCCESS = typeof SEARCH_REPOSITORY_SUCCESS;
export const SEARCH_REPOSITORY_FAILURE ='SEARCH_REPOSITORY_FAILURE';
export type SEARCH_REPOSITORY_FAILURE = typeof SEARCH_REPOSITORY_FAILURE;

/* Repository item*/


export const GET_REPOSITORY ='GET_REPOSITORY';
export type GET_REPOSITORY = typeof GET_REPOSITORY;
export const GETTING_REPOSITORY ='GETTING_REPOSITORY';
export type GETTING_REPOSITORY = typeof GETTING_REPOSITORY;
export const GET_REPOSITORY_SUCCESS ='GET_REPOSITORY_SUCCESS';
export type GET_REPOSITORY_SUCCESS = typeof GET_REPOSITORY_SUCCESS;
export const GET_REPOSITORY_FAILURE ='GET_REPOSITORY_FAILURE';
export type GET_REPOSITORY_FAILURE = typeof GET_REPOSITORY_FAILURE;



/* Repository item*/


export const GET_REPOSITORY_CONTRIBUTORS ='GET_REPOSITORY_CONTRIBUTORS';
export type GET_REPOSITORY_CONTRIBUTORS = typeof GET_REPOSITORY_CONTRIBUTORS;
export const GETTING_REPOSITORY_CONTRIBUTORS ='GETTING_REPOSITORY_CONTRIBUTORS';
export type GETTING_REPOSITORY_CONTRIBUTORS = typeof GETTING_REPOSITORY_CONTRIBUTORS;
export const GET_REPOSITORY_CONTRIBUTORS_SUCCESS ='GET_REPOSITORY_CONTRIBUTORS_SUCCESS';
export type GET_REPOSITORY_CONTRIBUTORS_SUCCESS = typeof GET_REPOSITORY_CONTRIBUTORS_SUCCESS;
export const GET_REPOSITORY_CONTRIBUTORS_FAILURE ='GET_REPOSITORY_CONTRIBUTORS_FAILURE';
export type GET_REPOSITORY_CONTRIBUTORS_FAILURE = typeof GET_REPOSITORY_CONTRIBUTORS_FAILURE;



/* Repository Commit item*/


export const GET_REPOSITORY_COMMITS ='GET_REPOSITORY_COMMITS';
export type GET_REPOSITORY_COMMITS = typeof GET_REPOSITORY_COMMITS;
export const GETTING_REPOSITORY_COMMITS ='GETTING_REPOSITORY_COMMITS';
export type GETTING_REPOSITORY_COMMITS = typeof GETTING_REPOSITORY_COMMITS;
export const GET_REPOSITORY_COMMITS_SUCCESS ='GET_REPOSITORY_COMMITS_SUCCESS';
export type GET_REPOSITORY_COMMITS_SUCCESS = typeof GET_REPOSITORY_COMMITS_SUCCESS;
export const GET_REPOSITORY_COMMITS_FAILURE ='GET_REPOSITORY_COMMITS_FAILURE';
export type GET_REPOSITORY_COMMITS_FAILURE = typeof GET_REPOSITORY_COMMITS_FAILURE;



/* Repository Commit item*/


export const GET_REPOSITORY_COMMITS_STATS ='GET_REPOSITORY_COMMITS_STATS';
export type GET_REPOSITORY_COMMITS_STATS = typeof GET_REPOSITORY_COMMITS_STATS;
export const GETTING_REPOSITORY_COMMITS_STATS ='GETTING_REPOSITORY_COMMITS_STATS';
export type GETTING_REPOSITORY_COMMITS_STATS = typeof GETTING_REPOSITORY_COMMITS_STATS;
export const GET_REPOSITORY_COMMITS_STATS_SUCCESS ='GET_REPOSITORY_COMMITS_STATS_SUCCESS';
export type GET_REPOSITORY_COMMITS_STATS_SUCCESS = typeof GET_REPOSITORY_COMMITS_STATS_SUCCESS;
export const GET_REPOSITORY_COMMITS_STATS_FAILURE ='GET_REPOSITORY_COMMITS_STATS_FAILURE';
export type GET_REPOSITORY_COMMITS_STATS_FAILURE = typeof GET_REPOSITORY_COMMITS_STATS_FAILURE;



